In [58]:
## importing important libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [59]:
df = pd.read_csv("../Datasets/Travel.csv")
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [60]:
df.isna().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   str
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   str
 7   Gender                    4888 non-null   str
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   str
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   str
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   str
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), str(6)
memory usage: 763.9 KB

In [62]:
df = df.drop('CustomerID', axis=1)

In [63]:
categorical_features = [feat for feat in df.columns if df[feat].dtype == 'str']
print(categorical_features)

['TypeofContact', 'Occupation', 'Gender', 'ProductPitched', 'MaritalStatus', 'Designation']

In [64]:
for feat in categorical_features:
    print('-------',feat,'-------')
    print(df[feat].value_counts())

------- TypeofContact -------
TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64
------- Occupation -------
Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64
------- Gender -------
Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64
------- ProductPitched -------
ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64
------- MaritalStatus -------
MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64
------- Designation -------
Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [65]:
df['Gender'] = df['Gender'].str.replace('Fe Male', 'Female')
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [66]:
df['MaritalStatus'] = df['MaritalStatus'].str.replace('Single', 'Unmarried')
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [67]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['TypeofContact'] = df['TypeofContact'].fillna(df['TypeofContact'].mode()[0])
df['DurationOfPitch'] = df['DurationOfPitch'].fillna(df['DurationOfPitch'].median())
df['NumberOfFollowups'] = df['NumberOfFollowups'].fillna(df['NumberOfFollowups'].mode()[0])
df['PreferredPropertyStar'] = df['PreferredPropertyStar'].fillna(df['PreferredPropertyStar'].mode()[0])
df['NumberOfTrips'] = df['NumberOfTrips'].fillna(df['NumberOfTrips'].median())
df['MonthlyIncome'] = df['MonthlyIncome'].fillna(df['MonthlyIncome'].median())
mode_val = df['NumberOfChildrenVisiting'].mode()
if not mode_val.empty:
    df['NumberOfChildrenVisiting'] = df['NumberOfChildrenVisiting'].fillna(mode_val[0])

In [68]:
df.isna().sum()

ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [69]:
# create new column for feature
df['TotalVisiting'] = df['NumberOfPersonVisiting'] + df['NumberOfChildrenVisiting']
df = df.drop(['NumberOfPersonVisiting', 'NumberOfChildrenVisiting'], axis=1)

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ProdTaken               4888 non-null   int64
 1   Age                     4888 non-null   float64
 2   TypeofContact           4888 non-null   str
 3   CityTier                4888 non-null   int64
 4   DurationOfPitch         4888 non-null   float64
 5   Occupation              4888 non-null   str
 6   Gender                  4888 non-null   str
 7   NumberOfFollowups       4888 non-null   float64
 8   ProductPitched          4888 non-null   str
 9   PreferredPropertyStar   4888 non-null   float64
 10  MaritalStatus           4888 non-null   str
 11  NumberOfTrips           4888 non-null   float64
 12  Passport                4888 non-null   int64
 13  PitchSatisfactionScore  4888 non-null   int64
 14  OwnCar                  4888 non-null   int64
 15  Designation             4888 non-null   str
 16  MonthlyIncome           4888 non-null   float64
 17  TotalVisiting           4888 non-null   float64
dtypes: float64(7), int64(5), str(6)
memory usage: 687.5 KB

In [71]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [72]:
numerical_features = [feat for feat in df.columns if feat not in categorical_features and feat != 'ProdTaken']
print(numerical_features)

['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting']

In [73]:
discrete_features = [feat for feat in numerical_features if len(df[feat].unique()) <=25 and feat != 'ProdTaken']
print(discrete_features)

['CityTier', 'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar', 'TotalVisiting']

In [74]:
X = df.drop('ProdTaken', axis=1)
y = df['ProdTaken']

In [75]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [76]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [77]:
scaler = StandardScaler()
ohe = OneHotEncoder(drop='first')

In [78]:
transformer = ColumnTransformer([
    ('OneHotEncoder', ohe, categorical_features),
    ('StandardScaler', scaler, numerical_features)
])

In [79]:
X_train = transformer.fit_transform(X_train)
X_test = transformer.transform(X_test)

In [82]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,-0.714031,-0.649789,0.280718,-0.727208,-1.217370,-0.632714,1.409081,0.781435,0.460318,-0.067869
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,-0.714031,-0.527737,-0.719632,1.768057,1.504605,-0.632714,1.409081,-1.279697,-1.005668,-0.777901
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.161582,1.281068,1.768057,-0.672975,1.580492,-0.046813,0.781435,-1.209722,-0.067869
3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.470853,-0.771841,0.280718,0.520424,-0.128580,1.580492,-0.046813,0.781435,-0.017750,0.642163
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.527737,1.281068,0.520424,2.593396,-0.632714,0.681134,-1.279697,-0.423411,-0.067869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3416,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.649789,1.281068,-0.727208,-0.672975,-0.632714,-1.502707,0.781435,-0.531926,0.642163
3417,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.470853,-0.893893,-0.719632,1.768057,-1.217370,-0.632714,1.409081,0.781435,1.512744,-0.067869
3418,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.470853,1.547143,0.280718,-0.727208,2.049001,-0.632714,-0.774760,0.781435,-0.357400,0.642163
3419,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.470853,1.791246,1.281068,-0.727208,-0.128580,-0.632714,-1.502707,0.781435,-0.250765,0.642163
3420,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.771841,0.280718,-0.727208,-1.217370,1.580492,-0.046813,-1.279697,-1.071680,-1.487933

In [86]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report,ConfusionMatrixDisplay, \
                            precision_score, recall_score, f1_score, roc_auc_score,roc_curve

In [87]:
models={
    "Logisitic Regression":LogisticRegression(),
    "Decision Tree":DecisionTreeClassifier(),
    "Random Forest":RandomForestClassifier(),
    "Gradient Boost":GradientBoostingClassifier(),
    "Adaboost":AdaBoostClassifier()
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Training set performance
    model_train_accuracy = accuracy_score(y_train, y_train_pred) # Calculate Accuracy
    model_train_f1 = f1_score(y_train, y_train_pred, average='weighted') # Calculate F1-score
    model_train_precision = precision_score(y_train, y_train_pred) # Calculate Precision
    model_train_recall = recall_score(y_train, y_train_pred) # Calculate Recall
    model_train_rocauc_score = roc_auc_score(y_train, y_train_pred)


    # Test set performance
    model_test_accuracy = accuracy_score(y_test, y_test_pred) # Calculate Accuracy
    model_test_f1 = f1_score(y_test, y_test_pred, average='weighted') # Calculate F1-score
    model_test_precision = precision_score(y_test, y_test_pred) # Calculate Precision
    model_test_recall = recall_score(y_test, y_test_pred) # Calculate Recall
    model_test_rocauc_score = roc_auc_score(y_test, y_test_pred) #Calculate Roc


    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Accuracy: {:.4f}".format(model_train_accuracy))
    print('- F1 score: {:.4f}'.format(model_train_f1))
    
    print('- Precision: {:.4f}'.format(model_train_precision))
    print('- Recall: {:.4f}'.format(model_train_recall))
    print('- Roc Auc Score: {:.4f}'.format(model_train_rocauc_score))

    
    
    print('----------------------------------')
    
    print('Model performance for Test set')
    print('- Accuracy: {:.4f}'.format(model_test_accuracy))
    print('- F1 score: {:.4f}'.format(model_test_f1))
    print('- Precision: {:.4f}'.format(model_test_precision))
    print('- Recall: {:.4f}'.format(model_test_recall))
    print('- Roc Auc Score: {:.4f}'.format(model_test_rocauc_score))

    
    print('='*35)
    print('\n')

Logisitic Regression
Model performance for Training set
- Accuracy: 0.8451
- F1 score: 0.8188
- Precision: 0.7101
- Recall: 0.3034
- Roc Auc Score: 0.6373
----------------------------------
Model performance for Test set
- Accuracy: 0.8432
- F1 score: 0.8193
- Precision: 0.6719
- Recall: 0.3139
- Roc Auc Score: 0.6393
===================================


Decision Tree
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9039
- F1 score: 0.9049
- Precision: 0.7301
- Recall: 0.7701
- Roc Auc Score: 0.8523
===================================


Random Forest
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9155
- F1 score: 0.9075
- Precision: 0.9360
- Recall: 0.5876
- Roc Auc Score: 0.7892
===================================


Gradient Boost
Model performance for Training set
- Accuracy: 0.8948
- F1 score: 0.8833
- Precision: 0.8803
- Recall: 0.5124
- Roc Auc Score: 0.7481
----------------------------------
Model performance for Test set
- Accuracy: 0.8766
- F1 score: 0.8628
- Precision: 0.7962
- Recall: 0.4562
- Roc Auc Score: 0.7147
===================================


Adaboost
Model performance for Training set
- Accuracy: 0.8433
- F1 score: 0.8084
- Precision: 0.7696
- Recall: 0.2430
- Roc Auc Score: 0.6130
----------------------------------
Model performance for Test set
- Accuracy: 0.8316
- F1 score: 0.7954
- Precision: 0.6484
- Recall: 0.2153
- Roc Auc Score: 0.5943
===================================

In [93]:
## HyperParameter Tuning
params = {
    "n_estimators": [50, 60, 70, 80, 90]
}

In [94]:
from sklearn.model_selection import GridSearchCV

In [95]:
grid = GridSearchCV(
    estimator=AdaBoostClassifier(),
    param_grid = params,
    cv = 5,
    verbose = 3,
    scoring='accuracy'
)

In [96]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV 1/5] END ...................n_estimators=50;, score=0.838 total time=   0.3s
[CV 2/5] END ...................n_estimators=50;, score=0.846 total time=   0.2s
[CV 3/5] END ...................n_estimators=50;, score=0.849 total time=   0.3s
[CV 4/5] END ...................n_estimators=50;, score=0.852 total time=   0.4s
[CV 5/5] END ...................n_estimators=50;, score=0.844 total time=   0.4s
[CV 1/5] END ...................n_estimators=60;, score=0.838 total time=   0.3s
[CV 2/5] END ...................n_estimators=60;, score=0.852 total time=   0.3s
[CV 3/5] END ...................n_estimators=60;, score=0.849 total time=   0.3s
[CV 4/5] END ...................n_estimators=60;, score=0.851 total time=   0.3s
[CV 5/5] END ...................n_estimators=60;, score=0.849 total time=   0.3s
[CV 1/5] END ...................n_estimators=70;, score=0.834 total time=   0.3s
[CV 2/5] END ...................n_estimators=70;, score=0.852 total time=   0.3s
[CV 3/5] END ...................n_estimators=70;, score=0.846 total time=   0.3s
[CV 4/5] END ...................n_estimators=70;, score=0.863 total time=   0.3s
[CV 5/5] END ...................n_estimators=70;, score=0.846 total time=   0.5s
[CV 1/5] END ...................n_estimators=80;, score=0.835 total time=   0.4s
[CV 2/5] END ...................n_estimators=80;, score=0.846 total time=   0.4s
[CV 3/5] END ...................n_estimators=80;, score=0.849 total time=   0.4s
[CV 4/5] END ...................n_estimators=80;, score=0.861 total time=   0.5s
[CV 5/5] END ...................n_estimators=80;, score=0.846 total time=   0.7s
[CV 1/5] END ...................n_estimators=90;, score=0.835 total time=   0.7s
[CV 2/5] END ...................n_estimators=90;, score=0.848 total time=   0.5s
[CV 3/5] END ...................n_estimators=90;, score=0.844 total time=   0.5s
[CV 4/5] END ...................n_estimators=90;, score=0.861 total time=   0.6s
[CV 5/5] END ...................n_estimators=90;, score=0.845 total time=   0.8s

GridSearchCV(cv=5, estimator=AdaBoostClassifier(),
             param_grid={'n_estimators': [50, 60, 70, 80, 90]},
             scoring='accuracy', verbose=3)

In [97]:
grid.best_params_

{'n_estimators': 70}

In [98]:
grid.best_score_

np.float64(0.8482942758355744)

In [99]:
y_pred = grid.predict(X_test)

In [101]:
accuracy_score(y_test, y_pred)

0.8377641445126107